const express=require('express')
const mongoose=require('mongoose')
const config=require('./utils/config')
const logger=require('./utils/logger')
const middleware=require('./utils/middleware')
const blogPostRouter=require('./controller/blog')
const userRouter = require('./controller/user')
const loginRouter = require('./controller/login')
const app=express()
mongoose.connect(config.MONGODB_URI)
app.use(express.json())
app.use(middleware.requestLogger)
app.use(middleware.tokenExtractor)
app.use('/api/blogs',blogPostRouter)
app.use('/api/users',userRouter)
app.use('/api/login', loginRouter)
app.use(middleware.unknownEndpoint)
app.use(middleware.errorHandler)

module.exports=app
